In [35]:
import pandas as pd
from random import randint

In [36]:
a=pd.read_csv('regional_carbon_intensity_2025_complete.csv')
a.head()

,from,to,regionid,shortname,forecast,index,datetime
0,2024-12-31T23:30Z,2025-01-01T00:00Z,1,North Scotland,0,very low,2024-12-31 23:30:00
1,2024-12-31T23:30Z,2025-01-01T00:00Z,2,South Scotland,6,very low,2024-12-31 23:30:00
2,2024-12-31T23:30Z,2025-01-01T00:00Z,3,North West England,4,very low,2024-12-31 23:30:00
3,2024-12-31T23:30Z,2025-01-01T00:00Z,4,North East England,11,very low,2024-12-31 23:30:00
4,2024-12-31T23:30Z,2025-01-01T00:00Z,5,Yorkshire,64,low,2024-12-31 23:30:00

In [37]:
# only keep numerical data
b=a[['regionid', 'forecast', 'datetime']]
# read in the data range
b.describe()

           regionid       forecast
count  208638.00000  208638.000000
mean        9.50000     128.728899
std         5.18814     100.961657
min         1.00000       0.000000
25%         5.00000      40.000000
50%         9.50000     113.000000
75%        14.00000     194.000000
max        18.00000     431.000000

In [39]:
# randomised CPU%
b['CPU(%)']=randint(1,100)
# corresponding energy usagage for 10 hours
b['Energy (kWh, 10h)']=b['CPU(%)']*0.003+0.2
# carbon emission using the regional carbon intensity forecast data
b['gCO2']=b['Energy (kWh, 10h)']*b['forecast']
# reserved hours = gCO2 emission /10 
b['Reserved_Hour_per_CO2']=b['gCO2']/10 
b['gCO2_per_Active_Compute_Hour']= b['Reserved_Hour_per_CO2']/b['CPU(%)']/100
b.head()

,regionid,forecast,datetime,CPU(%),"Energy (kWh, 10h)",gCO2,Reserved_Hour_per_CO2,gCO2_per_Active_Compute_Hour
0,1,0,2024-12-31 23:30:00,38,0.314,0.000,0.0000,0.000000
1,2,6,2024-12-31 23:30:00,38,0.314,1.884,0.1884,0.000050
2,3,4,2024-12-31 23:30:00,38,0.314,1.256,0.1256,0.000033
3,4,11,2024-12-31 23:30:00,38,0.314,3.454,0.3454,0.000091
4,5,64,2024-12-31 23:30:00,38,0.314,20.096,2.0096,0.000529

In [40]:
b.to_csv('data1_without_FU.csv')